### ISSUE TITLE
This file doesn't belong to a cookbook message - previously working

### ISSUE THREAD

**Issue by DBAYoder** [rdeavila/chef-server-file-upload#1]
When I do a Shift-Command-P and choose "Chef:Send entire cookbook to server", I am getting a "This file doesn't belong to a cookbook" message.  It does not matter if I am on a cookbook folder, recipe folder, or recipe (actual recipe.rb file), or whether there is code in the editor or not - all conditions report the same result.  I previously had it working, and don't know what has changed.  I am accessing VSCode on a Macbook Pro.

**Comment by rdeavila** [comment]
To be recognized as a cookbook, you workspace must start on the root of your chef repo, and the file must be inside the `cookbook` directory (or any other subdirectory below). With this, the `cookbook` directory will be the first part of file path on `vscode.workspace.asRelativePath`.

https://github.com/rdeavila/chef-server-file-upload/blob/f4a8e2c0124212e96446133a1e2cd8ad3948318b/src/extension.ts#L72-L78

**Comment by DBAYoder** [comment]
Thank you!  I switched out projects I was working on and when I came back to it, I opened an old entry (now removed from "open recent").
